language: ruby
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
- 1.9.2

before_script:
  - chmod 600 spec/fixtures/.netrc

script:
  - bundle exec rubocop
  - bundle exec rspec spec

deploy:
  provider: rubygems
  api_key:
    secure: g7xKyeiMs2o1HLokzOWCiLKxmTaEmuQDB0he9kxFhjqMLbRQHu1pVL0uE2bD0K/zq8Ebb+OPchVmej/6s5Be97AOK5d1wGdBAhXISwlxPoXxLJ6zU5DF1vjF3YCZK197z81ATcGcocsD2eYXZ4NzJcI+FW3kzO6QQhfHfUUeHvM=
  gem: bwapi
  on:
    repo: jonathanchrisp/bwapi
